require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'collaboratorapp' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTLinkingIOS',
  ]

  target 'collaboratorappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'collaboratorapp-tvOS' do
  # Pods for collaboratorapp-tvOS

  target 'collaboratorapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
