import Config from 'react-native-config';

const {
  API_LOCATION,
  HOST_URL,
  GOOGLE_MAPS_API_KEY,
  MAP_KIT_KEY,
  WEB_SITE_URL,
  APPCENTER_ANDROID_PRODUCTION,
  APPCENTER_ANDROID_STAGING,
  APPCENTER_IOS_PRODUCTION,
  APPCENTER_IOS_STAGING,
  ENVIRONMENT,
  HUAWEI_API_KEY,
  APP_STORE_APP_ID,
  PAYATCLIENTID,
  PAYATCLIENTSECRET,
  PAYATSCOPE,
  PAYATCLIENTREFERENCE,
  APP_SIGN_IN,
  APP_PASSWORD,
} = Config;
export default {
  accessTokenKey: 'access_token',
  hostUrl: HOST_URL,
  apiUrl: `${HOST_URL}${API_LOCATION}`,
  googleMapsApiKey: GOOGLE_MAPS_API_KEY,
  mapKitKey: MAP_KIT_KEY,
  webSiteUrl: WEB_SITE_URL,
  fcmTokenKey: 'fcmToken',
  pushKitEnabled: 'pushKitEnabled',
  pushKitTokenKey: 'pushKitToken',
  appCenterAndroid: APPCENTER_ANDROID_PRODUCTION,
  appCenterAndroidStaging: APPCENTER_ANDROID_STAGING,
  appCenterIos: APPCENTER_IOS_PRODUCTION,
  appCenterIosStaging: APPCENTER_IOS_STAGING,
  appEnvironment: ENVIRONMENT,
  huaweiApiKey: HUAWEI_API_KEY,
  hmsSiteApiUrl: 'https://siteapi.cloud.huawei.com/mapApi/v1/siteService',
  androidDownloadLink: 'https://play.google.com/store/apps/details?id=com.collaboratorapp',
  iOSDownloadLink: 'https://apps.apple.com/us/app/collab-citizen/id1557197011',
  huaweiDownloadAppLink: 'https://appgallery.huawei.com/app/C104847131',
  combinedLink: 'https://onelink.to/jjzt2k',
  appStoreAppId: APP_STORE_APP_ID,
  androidPackageId: 'com.collaboratorapp',
  paymentBaseUrl: 'https://citizencollab.collaboratoronline.com/webapitest/api/',
  payAtAuthUrl: 'https://payat.io:9443/oauth/v1/token',
  payAtClientId: PAYATCLIENTID,
  payAtClientSecret: PAYATCLIENTSECRET,
  payAtScope: PAYATSCOPE,
  payAtClientReference: PAYATCLIENTREFERENCE,
  isFirstTimeUserKey: 'isFirstTimeUserKey',
  accountTourEnabled: 'accountTourEnabled',
  appSignIn: APP_SIGN_IN,
  appPassword: APP_PASSWORD,
};
